# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: dirhtml
  configuration: docs/conf.py
<<<<<<< HEAD
  fail_on_warning: true
=======

# Optionally build your docs in additional formats such as PDF
# formats:
#  - pdf
#  - epub
>>>>>>> starbase/main

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - git fetch --tags --unshallow # Also fetch tags
<<<<<<< HEAD
      - git describe # Make sure we get a proper version
=======
>>>>>>> starbase/main
    post_system_dependencies:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
<<<<<<< HEAD
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --extra docs
=======
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --group docs
>>>>>>> starbase/main
