# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
---
# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - git submodule update --init -- docs/sphinx-starter-pack
      - make preparedocs
    post_install:
      - ./tools/mkdoclinks.sh

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: dirhtml
  fail_on_warning: true

# Build documentation with MkDocs
# mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

# Optionally set the version of Python
# and requirements required to build your docs
python:
  install:
    - requirements: requirements-doc.txt
    - method: pip
      path: .
