[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.mypy]
python_version = "3.8"
exclude = [
    "build",
    "results",
]
warn_unused_configs = true
warn_redundant_casts = true
strict_equality = true
strict_concatenate = true
#warn_return_any = true
disallow_subclassing_any = true
disallow_untyped_decorators = true
#disallow_any_generics = true

[[tool.mypy.overrides]]
module = ["rockcraft"]
disallow_untyped_defs = true
no_implicit_optional = true

[[tool.mypy.overrides]]
module = ["tests.*"]
strict = false

[[tool.mypy.overrides]]
module = ["craft_archives"]
ignore_missing_imports = true

[tool.pylint.messages_control]
disable = "too-many-ancestors,too-few-public-methods,fixme,unspecified-encoding,use-implicit-booleaness-not-comparison,unnecessary-lambda-assignment,line-too-long"

[tool.pylint.similarities]
min-similarity-lines=12

[tool.pylint.format]
max-line-length = "88"
max-locals = 16

[tool.pylint.MASTER]
extension-pkg-whitelist = [
    "pydantic"
]
load-plugins = "pylint_pytest"
