[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.pylint.messages_control]
disable = "too-many-ancestors,too-few-public-methods,fixme,unspecified-encoding,use-implicit-booleaness-not-comparison,unnecessary-lambda-assignment,line-too-long"

[tool.pylint.similarities]
min-similarity-lines=12

[tool.pylint.format]
max-line-length = "88"
max-locals = 16

[tool.pylint.MASTER]
extension-pkg-whitelist = [
    "pydantic"
]
load-plugins = "pylint_pytest"
