name: Bug report
description: Report a bug
labels: "Bug"
body:
  - type: checkboxes
    id: check-existing-issues
    attributes:
      label: Check existing issues
      options:
        - label: I've verified that this bug isn't described by any existing issues.
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      value: >
        <!-- Describe the bug, including any relevant context or screenshots. -->
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      value: >
        <!-- Provide step-by-step instructions to reproduce the bug. -->
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      value: >
        <!-- We need to understand the context in which Rockcraft failed. Please let us
        know if you are running Rockcraft in destructive mode, whether you are using LXD
        or Multipass, and which operating system you are running Rockcraft on. -->
    validations:
      required: true
  - type: textarea
    id: rockcraft_yaml
    attributes:
      label: rockcraft.yaml
      value: >
        <!-- If the issue is specific to a project, share its `rockcraft.yaml`. This
        field automatically renders as YAML, so you don't need to add special
        formatting. -->
      render: yaml
  - type: textarea
    id: logs
    attributes:
      label: Log output
      value: >
        <!-- Provide any relevant logging. This field automatically renders as
        a log, so you don't need to add special formatting. -->
      render: shell
