name: rockcraft
version: git
base: core22
summary: A craft like experience to create ROCKS
description: |
    Rockcraft aims to take the same primitives used in Charmcraft and Snapcraft
    to create OCI images.
confinement: classic
grade: devel
license: GPL-3.0

# https://github.com/snapcore/snapcraft/issues/4187
environment:
  PATH: "$SNAP/libexec/rockcraft:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  LD_LIBRARY_PATH: "$SNAP/none"

apps:
  rockcraft:
    command: bin/python $SNAP/bin/rockcraft

build-packages:
  - libapt-pkg-dev
  - libyaml-dev
  - python3.10-dev
  - pkg-config

parts:
  rockcraft-libs:
    plugin: nil
    build-attributes:
        - enable-patchelf
    stage-packages:
        - apt
        - apt-transport-https
        - apt-utils
        - binutils
        - gpg
        - gpgv
        - libpython3-stdlib
        - libpython3.10-stdlib
        - libpython3.10-minimal
        - python3-pip
        - python3-setuptools
        - python3-wheel
        - python3-venv
        - python3-minimal
        - python3-distutils
        - python3-pkg-resources
        - python3.10-minimal
        - fuse-overlayfs

  rockcraft:
    source: .
    plugin: python
    python-packages:
        - wheel
        - pip
        - setuptools
    python-requirements:
        - requirements-jammy.txt
        - requirements.txt
    build-attributes:
        - enable-patchelf
    build-environment:
        - "CFLAGS": "$(pkg-config python-3.10 yaml-0.1 --cflags)"
    organize:
        bin/craftctl: libexec/rockcraft/craftctl
    override-build: |
      craftctl default
  
      sed -i -e '1 s|^#!/.*|#!/snap/rockcraft/current/bin/python -E|' $CRAFT_PART_INSTALL/bin/craftctl
    after:
      - rockcraft-libs
  
  umoci:
    plugin: make
    source: https://github.com/opencontainers/umoci.git
    source-tag: v0.4.7
    make-parameters:
        - umoci.static
    override-build: |
        make umoci.static
        mkdir "$CRAFT_PART_INSTALL"/bin
        install -m755 umoci.static "$CRAFT_PART_INSTALL"/bin/umoci
    build-packages:
        - golang-go
        - make

  skopeo:
    plugin: nil
    source: https://github.com/containers/skopeo.git
    source-tag: v1.9.0
    override-build: |
        CGO=1 go build -ldflags -linkmode=external ./cmd/skopeo
        mkdir "$CRAFT_PART_INSTALL"/bin
        install -m755 skopeo "$CRAFT_PART_INSTALL"/bin/skopeo
    stage-packages:
        - libgpgme11
        - libassuan0
        - libbtrfs0
        - libdevmapper1.02.1
    build-attributes:
        - enable-patchelf
    build-snaps:
        - go/1.17/stable
    build-packages:
        - libgpgme-dev
        - libassuan-dev
        - libbtrfs-dev
        - libdevmapper-dev
        - pkg-config

  chisel:
    plugin: go
    source: https://github.com/canonical/chisel.git
    source-commit: bd27f8700cd7d2a6b4e0df6b10c3761c83a70485
    build-snaps:
      - go/1.18/stable
