name: rockcraft
base: core22
summary: A craft like experience to create rocks
description: |
    Rockcraft aims to take the same primitives used in Charmcraft and Snapcraft
    to create OCI images.
adopt-info: rockcraft
confinement: classic
license: GPL-3.0

# https://github.com/snapcore/snapcraft/issues/4187
environment:
  PATH: "$SNAP/libexec/rockcraft:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  LD_LIBRARY_PATH: "$SNAP/none"

apps:
  rockcraft:
    command: bin/python $SNAP/bin/rockcraft
  skopeo:
    command: bin/skopeo

build-packages:
  - libapt-pkg-dev
  - libffi-dev # for cffi (via pygit2)
  - libyaml-dev
  - python3.10-dev
  - pkg-config

parts:
  rockcraft-libs:
    plugin: nil
    build-attributes:
        - enable-patchelf
    stage-packages:
        - apt
        - apt-transport-https
        - apt-utils
        - binutils
        - gpg
        - gpgv
        - libpython3-stdlib
        - libpython3.10-stdlib
        - libpython3.10-minimal
        - python3-pip
        - python3-setuptools
        - python3-wheel
        - python3-venv
        - python3-minimal
        - python3-distutils
        - python3-pkg-resources
        - python3.10-minimal
        - fuse-overlayfs
    organize:
        "usr/bin/fuse-overlayfs": "libexec/rockcraft/fuse-overlayfs"

  libgit2: # part came from snapcraft@5fbaab144842f
    source: https://github.com/libgit2/libgit2/archive/refs/tags/v1.7.1.tar.gz
    source-checksum: sha256/17d2b292f21be3892b704dddff29327b3564f96099a1c53b00edc23160c71327
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - libssl-dev
    build-attributes:
      - enable-patchelf
    prime:
      - -usr/include

  rockcraft:
    source: .
    plugin: python
    python-packages:
        - wheel
        - pip
        - setuptools
    python-requirements:
        - requirements-jammy.txt
        - requirements.txt
    build-attributes:
        - enable-patchelf
    build-environment:
        - "CFLAGS": "$(pkg-config python-3.10 yaml-0.1 --cflags)"
    organize:
        bin/craftctl: libexec/rockcraft/craftctl
    override-build: |
      ${SNAP}/libexec/snapcraft/craftctl default

      version="$(python3 setup.py --version)"
      ${SNAP}/libexec/snapcraft/craftctl set version="$version"
      [ -n "$(echo $version | grep "post")" ] && grade=devel || grade=stable
      ${SNAP}/libexec/snapcraft/craftctl set grade="${grade}"

      sed -i -e '1 s|^#!/.*|#!/snap/rockcraft/current/bin/python -E|' $CRAFT_PART_INSTALL/bin/craftctl
    after:
      - rockcraft-libs
      - libgit2

  umoci:
    plugin: make
    source: https://github.com/opencontainers/umoci.git
    source-tag: v0.4.7
    make-parameters:
        - umoci.static
    override-build: |
        make umoci.static
        mkdir "$CRAFT_PART_INSTALL"/bin
        install -m755 umoci.static "$CRAFT_PART_INSTALL"/bin/umoci
    build-packages:
        - make
    build-snaps:
        - go/1.21/stable

  skopeo:
    plugin: nil
    source: https://github.com/containers/skopeo.git
    source-tag: v1.14.2
    override-build: |
        CGO=1 go build -ldflags -linkmode=external ./cmd/skopeo
        mkdir "$CRAFT_PART_INSTALL"/bin
        install -m755 skopeo "$CRAFT_PART_INSTALL"/bin/skopeo
    stage-packages:
        - libgpgme11
        - libassuan0
        - libbtrfs0
        - libdevmapper1.02.1
    build-attributes:
        - enable-patchelf
    build-snaps:
        - go/1.21/stable
    build-packages:
        - libgpgme-dev
        - libassuan-dev
        - libbtrfs-dev
        - libdevmapper-dev
        - pkg-config

  chisel:
    plugin: nil
    stage-snaps:
      - chisel/latest/candidate
    organize: 
      bin/chisel: libexec/rockcraft/chisel
    stage:
      - libexec/rockcraft/chisel
