name: rockcraft
base: core24
summary: A craft like experience to create rocks
description: |
  Rockcraft aims to take the same primitives used in Charmcraft and Snapcraft
  to create OCI images.
adopt-info: rockcraft
confinement: classic
license: GPL-3.0

# https://github.com/snapcore/snapcraft/issues/4187
environment:
  PATH: "$SNAP/libexec/rockcraft:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  LD_LIBRARY_PATH: "$SNAP/none"

platforms:
  amd64:
  arm64:
  armhf:
  riscv64:
  s390x:
  ppc64el:

apps:
  rockcraft:
    command: bin/python $SNAP/bin/rockcraft
    completer: completion.sh
  skopeo:
    command: bin/skopeo

build-packages:
  - libapt-pkg-dev
  - libffi-dev # for cffi (via pygit2)
  - libxml2-dev # for lxml (craft-parts)
  - libxslt1-dev
  - libyaml-dev
  - python3.12-dev
  - pkg-config

parts:
  rockcraft-libs:
    after:
      - skopeo # to correctly patch gpg and gpgv
    plugin: nil
    build-attributes:
      - enable-patchelf
    stage-packages:
      - apt
      - apt-transport-https
      - apt-utils
      - binutils
      - gpg
      - gpgv
      - libpython3-stdlib
      - libpython3.12-stdlib
      - libpython3.12-minimal
      - libxml2 # for lxml (craft-parts)
      - libxslt1.1
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - python3-minimal
      - python3-pkg-resources
      - python3.12-minimal

  # Build our own version of fuse-overlayfs due to https://github.com/containers/fuse-overlayfs/issues/429
  # The apt and Launchpad repositories as of 23/07/25 do not have a sufficiently new version to get this patch
  fuse-overlayfs:
    source: https://github.com/containers/fuse-overlayfs.git
    source-tag: v1.15
    plugin: autotools
    build-attributes:
      - enable-patchelf
    build-packages:
      - libfuse3-dev
      - pkgconf
    stage-packages:
      - libfuse3-3
    organize:
      "usr/local/bin/fuse-overlayfs": "libexec/rockcraft/fuse-overlayfs"

  rockcraft-scripts:
    source: ./snap/local
    plugin: dump
    organize:
      craft.git: libexec/rockcraft/craft.git
      # Put sitecustomize in site-packages
      sitecustomize.py: lib/python3.12/site-packages/sitecustomize.py

  git:
    plugin: nil
    stage-packages: [git]
    build-attributes:
      - enable-patchelf
    prime:
      - "-usr/bin"
      - "-usr/share/doc"
      - "-usr/share/man"
      # perl is part of the core22 / core24
      - "-usr/share/perl"
      - "-usr/lib/x86_64-linux-gnu/perl"
      - "-usr/lib/x86_64-linux-gnu/libperl*"
      - "-usr/lib/x86_64-linux-gnu/libgdbm*"

  libgit2: # part came from snapcraft@5fbaab144842f
    source: https://github.com/libgit2/libgit2/archive/refs/tags/v1.9.1.tar.gz
    source-checksum: sha256/14cab3014b2b7ad75970ff4548e83615f74d719afe00aa479b4a889c1e13fc00
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTS=OFF
    build-packages:
      - libssl-dev
    build-attributes:
      - enable-patchelf
    prime:
      - -usr/include

  python3-apt:
    plugin: nil
    build-attributes:
      - enable-patchelf
    stage-packages:
      - python3-apt
    organize:
      "usr/lib/python3/dist-packages/*": "lib/python3.12/site-packages/"

  rockcraft:
    source: .
    plugin: uv
    build-attributes:
      - enable-patchelf
    build-packages:
      - cargo
    build-snaps:
      - astral-uv
    build-environment:
      - "CFLAGS": "$(pkg-config python-3.12 yaml-0.1 --cflags)"
      - UV_FROZEN: "true"
      - UV_NO_BINARY: "true"
      # Parallel make jobs for things like python-apt
      - MAKEOPTS: -j$(nproc --all)
      - UV_COMPILE_BYTECODE: "true"
    uv-extras:
      # Rockcraft itself doesn't interact with the Store at the moment, but
      # craft-application plugins might.
      - store
    organize:
      bin/craftctl: libexec/rockcraft/craftctl
      # Extensions currently expect to find data files in share/rockcraft/
      "**/site-packages/extensions": share/rockcraft/extensions
    override-build: |
      ${SNAP}/libexec/snapcraft/craftctl default

      version="$(uv pip show rockcraft | grep "Version:" | cut -d' ' -f2)"
      ${SNAP}/libexec/snapcraft/craftctl set version="$version"

      [ -n "$(echo $version | grep "post")" ] && grade=devel || grade=stable
      ${SNAP}/libexec/snapcraft/craftctl set grade="${grade}"

      sed -i -e '1 s|^#!/.*|#!/snap/rockcraft/current/bin/python -E|' $CRAFT_PART_INSTALL/bin/craftctl

      # Fix the Python executable from uv, which had bad symlinks
      rm $CRAFT_PART_INSTALL/bin/python*
      ln -s ../usr/bin/python3 $CRAFT_PART_INSTALL/bin/python3
      ln -s python3 $CRAFT_PART_INSTALL/bin/python
    after:
      - rockcraft-libs
      - libgit2
      - python3-apt

  bash-completion:
    after: [rockcraft]
    plugin: nil
    build-environment:
      - PYTHONPATH: $CRAFT_STAGE/lib/python3.12/site-packages
      # so that rockcraft can find libgit2.so.1.9
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    override-build: |
      python3 -m craft_cli.completion $CRAFT_PROJECT_NAME rockcraft.cli:get_app_info \
        > $CRAFT_PART_INSTALL/completion.sh

  umoci:
    plugin: make
    source: https://github.com/opencontainers/umoci.git
    source-tag: v0.6.0
    make-parameters:
      - umoci.static
    override-build: |
      make umoci.static
      mkdir "$CRAFT_PART_INSTALL"/bin
      install -m755 umoci.static "$CRAFT_PART_INSTALL"/bin/umoci
    build-packages:
      - make
    build-snaps:
      - go

  skopeo:
    plugin: nil
    source: https://github.com/containers/skopeo.git
    source-tag: v1.20.0
    override-build: |
      CGO=1 go build -ldflags -linkmode=external ./cmd/skopeo
      mkdir "$CRAFT_PART_INSTALL"/bin
      install -m755 skopeo "$CRAFT_PART_INSTALL"/bin/skopeo
    stage-packages:
      - libgpgme11t64
      - libassuan0
      - libbtrfs0t64
      - libdevmapper1.02.1
    build-attributes:
      - enable-patchelf
    build-snaps:
      - go
    build-packages:
      - libgpgme-dev
      - libassuan-dev
      - libbtrfs-dev
      - libdevmapper-dev
      - pkg-config

  chisel:
    plugin: nil
    stage-snaps:
      - chisel/latest/candidate
    organize:
      bin/chisel: libexec/rockcraft/chisel
    stage:
      - libexec/rockcraft/chisel

  spread:
    plugin: go
    source: https://github.com/canonical/spread.git
    source-commit: d6447c43754c8ca0741901e9db73d5fdb4d21c93 # 'main' as of 28-March-2025
    build-snaps:
      - go
    build-attributes:
      - enable-patchelf
    build-environment:
      - CGO_ENABLED: 0
      - GOFLAGS: -trimpath -ldflags=-w -ldflags=-s
    organize:
      bin/spread: libexec/rockcraft/craft.spread
    stage:
      - libexec/rockcraft/

  # Add the project schema to the snap
  schema:
    plugin: dump
    source: ./schema
    organize:
      "*": schema/
