name: rockcraft
version: git
base: core20
summary: A craft like experience to create ROCKS
description: |
    Rockcraft aims to take the same primitives used in Charmcraft and Snapcraft
    to create OCI images.
confinement: classic
grade: devel
license: GPL-3.0

apps:
  rockcraft:
    command: bin/python $SNAP/bin/rockcraft
    environment:
      PATH: "$SNAP/libexec/rockcraft:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$SNAP/usr/bin:$SNAP/bin"

build-packages:
  - libapt-pkg-dev
  - libyaml-dev
  - python3.8-dev
  - pkg-config

parts:
  rockcraft-libs:
    plugin: nil
    stage-packages:
        - apt
        - apt-transport-https
        - apt-utils
        - binutils
        - gpg
        - gpgv
        - libpython3-stdlib
        - libpython3.8-stdlib
        - libpython3.8-minimal
        - python3-pip
        - python3-setuptools
        - python3-wheel
        - python3-venv
        - python3-minimal
        - python3-distutils
        - python3-pkg-resources
        - python3.8-minimal
        - fuse-overlayfs

  rockcraft:
    source: .
    plugin: python
    python-packages:
        - wheel
        - pip
        - setuptools
    requirements:
        - requirements-focal.txt
        - requirements.txt
    build-environment:
        - "CFLAGS": "$(pkg-config python-3.8 yaml-0.1 --cflags)"
    after: [rockcraft-libs]
    override-build: |
      snapcraftctl build
      # python3 fixup symlink (snapcraft bug)
      ln -sf ../usr/bin/python3.8 $SNAPCRAFT_PART_INSTALL/bin/python3
        mkdir -p $SNAPCRAFT_PART_INSTALL/libexec/rockcraft
        mv $SNAPCRAFT_PART_INSTALL/bin/craftctl $SNAPCRAFT_PART_INSTALL/libexec/rockcraft/
        sed -i -e '1 s|^#!/.*|#!/snap/rockcraft/current/bin/python|' $SNAPCRAFT_PART_INSTALL/libexec/rockcraft/craftctl

  umoci:
    plugin: make
    source: https://github.com/opencontainers/umoci.git
    source-tag: v0.4.7
    make-parameters:
        - umoci.static
    override-build: |
        make umoci.static
        mkdir "$SNAPCRAFT_PART_INSTALL"/bin
        install -m755 umoci.static "$SNAPCRAFT_PART_INSTALL"/bin/umoci
    build-packages:
        - golang-go
        - make

  skopeo:
    plugin: nil
    source: https://github.com/containers/skopeo.git
    source-tag: v1.9.0
    override-build: |
        CGO=1 go build -ldflags -linkmode=external ./cmd/skopeo
        mkdir "$SNAPCRAFT_PART_INSTALL"/bin
        install -m755 skopeo "$SNAPCRAFT_PART_INSTALL"/bin/skopeo
    stage-packages:
        - libgpgme11
        - libassuan0
        - libbtrfs0
        - libdevmapper1.02.1
    build-snaps:
        - go/1.17/stable
    build-packages:
        - libgpgme-dev
        - libassuan-dev
        - libbtrfs-dev
        - libdevmapper-dev
        - pkg-config
